# Generated by Django 4.2.4 on 2023-09-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0018_auto_20201015_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_registered',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='marital_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Separated', 'Separated'), ('Divorced', 'Divorced')], default='Single', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nid_number',
            field=models.CharField(default='1199080063332114', max_length=16, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Oncologist', 'Oncologist'), ('Neurologist', 'Neurologist'), ('Orthopedicsist', 'Orthopedicsist'), ('Dermatologist', 'Dermatologist'), ('Pediatrist', 'Pediatrist'), ('Gynecologist', 'Gynecologist'), ('Urologist', 'Urologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Internist', 'Internist'), ('Radiologist', 'Radiologist'), ('Anesthesiologist', 'Anesthesiologist'), ('General Surgery', 'General Surgery')], default='Cardiologist', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='work_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Oncology', 'Oncology'), ('Neurology', 'Neurology'), ('Orthopedics', 'Orthopedics'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Gynecology', 'Gynecology'), ('Urology', 'Urology'), ('Ophthalmology', 'Ophthalmology'), ('Internal Medicine', 'Internal Medicine'), ('Radiology', 'Radiology'), ('Anesthesiology', 'Anesthesiology'), ('Emergency Medicine', 'Emergency Medicine'), ('General Surgery', 'General Surgery')], default='Cardiology', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
