# Generated by Django 4.2.4 on 2023-09-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_remove_patient_symptoms_patient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nid_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
