# Generated by Django 4.2.4 on 2023-09-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_alter_patient_date_of_birth_alter_patient_nid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(default='2023-09-01'),
        ),
    ]
