# Generated by Django 4.2.4 on 2023-09-03 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_alter_patient_admitdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='symptoms',
        ),
    ]
