# Generated by Django 4.2.4 on 2023-09-03 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_remove_patientdischargedetails_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('consultation_date', models.DateField(auto_now=True)),
                ('complain', models.TextField()),
                ('diagnosis_note', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('insurance_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('insurance_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('category_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription_note', models.TextField()),
                ('prescription_date', models.DateField(auto_now=True)),
                ('consomation_condition', models.TextField(blank=True, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.consultation')),
            ],
        ),
        migrations.CreateModel(
            name='PatientsInsurance',
            fields=[
                ('patient_insurance_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('patient_percentage', models.IntegerField()),
                ('insurance_percentage', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.insurancecompany')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ExamTestOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_date', models.DateField(auto_now=True)),
                ('exams_result', models.CharField(blank=True, max_length=200, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.consultation')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.exam')),
            ],
        ),
    ]
